### ISSUE TITLE
[BUG]: How to solve this problem

### ISSUE THREAD

**Issue by WOLFxxxxxx** [PilotLightTech/pilotlight#69]
### What is the issue?

A bug happened!
![Capture](https://github.com/user-attachments/assets/d6848f4d-f293-4868-a96a-7123e1fda70f)

### Platform

Windows

### Graphics Backend

Vulkan

### System

Image

**Comment by hoffstadt** [comment]
Hey! You either ran out of VRAM or you didn't download the assets. Did you follow these [instructions](https://github.com/PilotLightTech/pilotlight/wiki/Building)?

**Comment by WOLFxxxxxx** [comment]
Ps ///intel core quad///gtx 950 2gb//Ram 4 🫣

**Comment by WOLFxxxxxx** [comment]
![Capture](https://github.com/user-attachments/assets/a0b4ebaa-7a8a-402c-a42c-a659c04bee17)

**Comment by hoffstadt** [comment]
Yeah a lot of optimization is left to be done! The examples should work fine though! Let me know how those go!

**Comment by WOLFxxxxxx** [comment]
Same error message
![Screenshot_٢٠٢٤-١٠-٠٥-١٣-٤٨-٥١-٨٠٤_com android chrome-edit](https://github.com/user-attachments/assets/17551123-1c18-45aa-8dac-817c1e1981ba)

**Comment by WOLFxxxxxx** [comment]
Thank you, I did the same

**Comment by WOLFxxxxxx** [comment]
But when I press Maximze it crashes
![Capture](https://github.com/user-attachments/assets/5dbb2947-cbaa-4af9-8692-3b59b4e68a92)

**Comment by hoffstadt** [comment]
You are most likely running out of vram. I have alot of work to do for optimizing memory usage.  If you read through the app code, you should lower the number of shadow cascades.

**Comment by WOLFxxxxxx** [comment]
Where can I find this example?♥️
![Screenshot_٢٠٢٤-١٠-٠٥-١٧-٠٨-٥٥-٩٥٤_com android chrome-edit](https://github.com/user-attachments/assets/ffa59788-a6f0-423d-bf04-7cdf48da7ddc)
