### ISSUE TITLE
Add children and parents to entities and objects

### ISSUE THREAD

**Issue by WOLFxxxxxx** [PilotLightTech/pilotlight#70]
### What is the feature?

The lists need to be modified and parents and children added
![A1](https://github.com/user-attachments/assets/7e3539fe-51c9-4274-bbec-1b859a98d480)
![A2](https://github.com/user-attachments/assets/3d28a08a-3337-4134-b176-597df7310639)

### Desribe alternatives you have considered?

.

### System

None

**Comment by WOLFxxxxxx** [comment]
When 10 skeletons are added, the entities become incomprehensible and unorganized

**Comment by hoffstadt** [comment]
This is actually on my internal list. Keep in mind that the current sandbox (including this helper tools) are still more for testing internal systems. This will greatly improve and change once the internal systems are complete and I begin working on user facing tools (like the ecs tool).
