### ISSUE TITLE
I hope you improve the code to become like raylib

### ISSUE THREAD

**Issue by WOLFxxxxxx** [PilotLightTech/pilotlight#71]
### What is the feature?

![Screenshot_٢٠٢٤-١٠-١٥-١٨-٥٧-٠٣-٠٠٥_com android chrome-edit](https://github.com/user-attachments/assets/997fac06-1239-4785-af1c-ad384f1f6dab)

### Desribe alternatives you have considered?

.

### System

None

**Comment by hoffstadt** [comment]
Hi, do you mean in terms of simplicity?

**Comment by WOLFxxxxxx** [comment]
Yes

**Comment by hoffstadt** [comment]
Lol. Yes the code will get simpler. What you are seeing now is still the "low level" APIs. Simpler APIs will be build on top of these as the lower ones become stable.
